class CitiesListHelper {
  static const List<String> cities = <String>[
    'Tunis',
    'Sousse',
    'Sahline',
    'Madrid',
    'London',
    'Paris',
    'Berlin',
    'Rome',
    'Moscow',
    'Tokyo',
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'Charlotte',
    'San Francisco',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Washington',
    'Boston',
    'El Paso',
    'Nashville',
    'Detroit',
    'Oklahoma City',
    'Portland',
    'Las Vegas',
    'Memphis',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Mesa',
    'Sacramento',
    'Atlanta',
    'Kansas City',
    'Colorado Springs',
    'Miami',
    'Raleigh',
    'Omaha',
    'Long Beach',
    'Virginia Beach',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Arlington',
    'Tampa',
    'New Orleans',
    'Wichita',
    'Cleveland',
    'Bakersfield',
    'Aurora',
    'Anaheim',
    'Honolulu',
    'Santa Ana',
    'Riverside',
    'Corpus Christi',
    'Lexington',
    'Stockton',
    'St. Louis',
    'Saint Paul',
    'Henderson',
    'Pittsburgh',
    'Cincinnati',
    'Anchorage',
    'Greensboro',
    'Plano',
    'Newark',
    'Lincoln',
    'Toledo',
    'Orlando',
    'Chula Vista',
    'Irvine',
    'Fort Wayne',
    'Jersey City',
    'Durham',
    'St. Petersburg',
    'Laredo',
    'Buffalo',
    'Madison',
    'Lubbock',
    'Chandler',
    'Scottsdale',
    'Glendale',
    'Reno',
    'Norfolk',
    'Winston–Salem',
    'North Las Vegas',
    'Irving',
    'Chesapeake',
    'Gilbert',
    'Hialeah',
    'Garland',
    'Fremont',
    'Baton Rouge',
    'Richmond',
    'Boise',
    'San Bernardino',
    'Spokane',
    'Birmingham',
    'Modesto',
    'Des Moines',
    'Rochester',
    'Tacoma',
    'Fontana',
    'Oxnard',
    'Moreno Valley',
    'Fayetteville',
    'Huntington Beach',
    'Yonkers',
    'Glendale',
    'Aurora',
    'Montgomery',
    'Columbus',
    'Amarillo',
    'Little Rock',
    'Akron',
    'Shreveport',
    'Augusta',
    'Grand Rapids',
    'Mobile',
    'Salt Lake City',
    'Huntsville',
    'Tallahassee',
    'Grand Prairie',
    'Overland Park',
    'Knoxville',
    'Worcester',
    'Brownsville',
    'Newport News',
    'Santa Clarita',
    'Port St. Lucie',
    'Providence',
    'Fort Lauderdale',
    'Chattanooga',
    'Tempe',
    'Oceanside',
    'Garden Grove',
    'Rancho Cucamonga',
    'Santa Rosa',
    'Peoria',
    'Rockford',
    'Springfield',
    'Cape Coral',
    'Santa Clarita',
    'Sioux Falls',
    'Port St. Lucie',
    'Grand Prairie',
    'Overland Park',
    'Knoxville',
    'Worcester',
    'Brownsville',
    'Vancouver',
    'Fort Lauderdale',
    'Chattanooga',
    'Tempe',
    'Oceanside',
    'Garden Grove',
    'Rancho Cucamonga',
    'Santa Rosa',
    'Ontario',
    'Corona',
    'Elk Grove',
    'Garden Grove',
    'Palmdale',
    'Hayward',
    'Lancaster',
    'Salinas',
    'Sunnyvale',
    'Pomona',
    'Escondido',
    'Kansas City',
    'Hollywood',
    'Lakewood',
    'Clarksville',
    'Pembroke Pines',
    'Salem',
    'Springfield',
    'Pasadena',
    'Orange',
    'Fullerton',
    'Killeen',
    'Frisco',
    'Hampton',
    'McAllen',
    'Warren',
    'Bellevue',
    'West Valley City',
    'Columbia',
    'Olathe',
    'Sterling Heights',
    'New Haven',
    'Miramar',
    'Waco',
    'Thousand Oaks',
    'Cedar Rapids',
    'Charleston',
    'Visalia',
    'Topeka',
    'Elizabeth',
    'Gainesville',
    'Thornton',
    'Roseville',
    'Carrollton',
    'Coral Springs',
    'Stamford',
    'Simi Valley',
    'Concord',
    'Hartford',
    'Kent',
    'Lafayette',
    'Midland',
    'Surprise',
    'Denton',
    'Victorville',
    'Evansville',
    'Santa Clara',
    'Abilene',
    'Athens',
    'Vallejo',
    'Allentown',
    'Norman',
    'Beaumont',
    'Independence',
    'Murfreesboro',
    'Ann Arbor',
    'Springfield',
    'Berkeley',
    'Peoria',
    'Provo',
    'El Monte',
    'Columbia',
    'Lansing',
    'Fargo',
    'Downey',
    'Costa Mesa',
    'Wilmington',
    'Arvada',
    'Inglewood',
    'Miami Gardens',
    'Carlsbad',
    'Westminster',
    'Rochester',
    'Odessa',
    'Manchester',
    'Elgin',
    'West Jordan',
    'Round Rock',
    'Clearwater',
    'Waterbury',
    'Gresham',
    'Fairfield',
    'Billings',
    'Lowell',
    'San Buenaventura (Ventura)',
    'Pueblo',
    'High Point',
    'West Covina',
    'Richmond',
    'Murrieta',
    'Cambridge',
    'Antioch',
    'Temecula',
    'Norwalk',
    'Centennial',
    'Everett',
    'Palm Bay',
    'Wichita Falls',
    'Green Bay',
    'Daly City',
    'Burbank',
    'Richardson',
    'Pompano Beach',
    'North Charleston',
    'Broken Arrow',
    'Boulder',
    'West Palm Beach',
    'Santa Maria',
    'El Cajon',
    'Davenport',
    'Rialto',
    'Las Cruces',
    'San Mateo',
    'Lewisville',
    'South Bend',
    'Lakeland',
    'Erie',
    'Tyler',
    'Pearland',
    'College Station',
    'Kenosha',
    'Sandy Springs',
    'Clovis',
    'Flint',
    'Roanoke',
    'Albany',
    'Jurupa Valley',
    'Compton',
    'San Angelo',
    'Hillsboro',
    'Lawton',
    'Renton',
    'Vista',
    'Davie',
    'Greeley',
    'Mission Viejo',
    'Portsmouth',
    'Dearborn',
    'South Gate',
    'Tuscaloosa',
    'Livonia',
    'New Bedford',
    'Vacaville',
    'Brockton',
    'Roswell',
    'Beaverton',
    'Quincy',
    'Sparks',
    'Yakima',
    "Lee's Summit",
    'Federal Way',
    'Carson City',
    'Santa Monica',
    'Hesperia',
    'Allen',
    'Rio Rancho',
    'Yuma',
    'Westminster',
    'Orem',
    'Lynn',
    'Redding'
  ];
}
