name: weather_app
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.0.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
  weather_icons: ^3.0.0
  shared_preferences: ^2.2.2
  toggle_switch: ^2.2.1
  autocomplete_textfield: ^2.0.1
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/images/bg.jpg"
  image: "assets/icons/app_icon.png"
